spring:
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5433/smart-home-db"
    username: "postgres"
    password: "postgres"
#  sql:
#    init:
#      data-locations: data.sql

logging:
  level:
    ru.yandex.practicum: debug
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

server:
  port: 0