grpc:
  client:
    collector:
      address: 'static://127.0.0.1:9090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
sensor:
  motionSensors:
    - id: "motion-1"
      linkQuality:
        minValue: 0
        maxValue: 100
      voltage:
        minValue: 0
        maxValue: 220
    - id: "motion-2"
      linkQuality:
        minValue: 50
        maxValue: 60
      voltage:
        minValue: 100
        maxValue: 220
  switchSensors:
    - id: "switch-1"
  temperatureSensors:
    - id: "temperature-1"
      temperature:
        minValue: -20
        maxValue: 30
    - id: "temperature-2"
      temperature:
        minValue: 0
        maxValue: 50
  lightSensors:
    - id: "light-1"
      luminosity:
        minValue: 100
        maxValue: 800
    - id: "light-2"
      luminosity:
        minValue: 200
        maxValue: 1000
  climateSensors:
    - id: "climate-1"
      temperature:
        minValue: 10
        maxValue: 25
      humidity:
        minValue: 30
        maxValue: 60
      co2Level:
        minValue: 400
        maxValue: 1000
    - id: "climate-2"
      temperature:
        minValue: 15
        maxValue: 30
      humidity:
        minValue: 40
        maxValue: 65
      co2Level:
        minValue: 300
        maxValue: 800