kafka:
  bootstrap-servers: localhost:9092
  topics:
    snapshots: "telemetry.snapshots.v1"
    hubs: "telemetry.hubs.v1"
  group-id:
    snapshots: telemetry.analyzer.snapshot
    hubs: telemetry.analyzer.hub

server:
  port: 0

grpc:
  client:
    hub-router:
      address: 'discovery:///hub-router'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

spring:
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5433/smarthome"
    username: "postgres"
    password: "postgres"
#    data: classpath:data.sql
  sql:
    init:
      data-locations: classpath:data.sql
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    ru.yandex.practicum: debug
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace